name: 'baralgae_demo'
version: '1.0.0'
config-version: 2

# איזה profile לשימוש
profile: 'baralgae_demo'

# היכן dbt מחפש קבצים
model-paths: ['models']
seed-paths: ['seeds']
macro-paths: ['macros']
snapshot-paths: ['snapshots']
test-paths: ['tests']

# quoting (נוח ל-Postgres/Redshift)
quoting:
  database: false
  schema: false
  identifier: false

# ברירת מחדל לשכבות
models:
  baralgae_demo:
    +materialized: view
    +tags: ['baralgae']
    staging:
      +materialized: view
      +tags: ['staging']
    intermediate:
      +materialized: ephemeral   # או 'view' אם אתה מעדיף דיבוג קל
      +tags: ['intermediate']
    marts:
      +materialized: table
      +tags: ['marts','gold']

# seeds נכנסים לסכימה 'raw' בדמו
seeds:
  baralgae_demo:
    +schema: raw
    +quote_columns: false

# snapshots יישמרו בסכימה נפרדת
snapshots:
  baralgae_demo:
    +target_schema: snapshots

# משתנים כלליים (דמו/פרוד)
vars:
  bronze_bucket: "{{ env_var('BRONZE_BUCKET','baralgae-demo') }}"
  silver_bucket: "{{ env_var('SILVER_BUCKET','baralgae-demo') }}"
  external_schema: "{{ env_var('REDSHIFT_EXTERNAL_SCHEMA','ext_demo') }}"