name: CI/CD Pipeline
on:
  push: { branches: [ main ] }
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: '3.12'
      DBT_PROFILES_DIR: transform/dbt
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install deps (demo only)
        run: |
          python -m pip install --upgrade pip
          pip install dbt-postgres==1.7.19
          pip install -r requirements-dev.txt

      - name: Set env (demo)
        run: |
          {
            echo "PGHOST=localhost"
            echo "PGPORT=5432"
            echo "PGDATABASE=test_db"
            echo "PGUSER=postgres"
            echo "PGPASSWORD=postgres"
          } >> $GITHUB_ENV

      - name: dbt compile
        working-directory: transform/dbt
        run: dbt deps && dbt compile
